<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>

    <Description>
      Provides foundational abstractions for text templating, including the TextTemplate&lt;TModel&gt; base class
      and ITextTemplateRenderContext interface, to be used by templating engine implementations
      such as Razor-based text templates.
    </Description>
    <PackageTags>text;templating;template;foundation;razor;abstraction;dotnet;posinformatique</PackageTags>
    <PackageReleaseNotes>
      $([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/CHANGELOG.md"))
    </PackageReleaseNotes>

  </PropertyGroup>

  <ItemGroup>
    <None Remove="CHANGELOG.md" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="CHANGELOG.md" Pack="false" />
    <Content Include="Icon.png" Pack="true" PackagePath="" />
    <Content Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>