<Project>

  <!-- Imports the parent Directory.Build.props if exist -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  
  <!-- Common NuGet packages -->
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport"/>
    <PackageReference Include="Moq"/>
    <PackageReference Include="PosInformatique.Moq.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    
    <!-- Required by XUnit v3 -->
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <EnableVSTestRunner>false</EnableVSTestRunner>

    <!-- Same code coverage configuration for all the test projects -->
    <RunSettingsFilePath>$(SolutionDir)\CodeCoverage.runsettings</RunSettingsFilePath>

    <!-- Disable packaging -->
    <IsPackable>false</IsPackable>
    
    <!-- Disable the StyleCop 'XML comment analysis is disabled due to project configuration' warning. -->
    <NoWarn>$(NoWarn);SA0001;EnableGenerateDocumentationFile</NoWarn>
  </PropertyGroup>

  <!-- Add the default using directive for all tests code -->
  <ItemGroup>
    <Using Include="AwesomeAssertions" />
    <Using Include="Moq" />
    <Using Include="Xunit" />
  </ItemGroup>

  <!-- Add the InternalsVisibleToAttribute for the tests -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
