<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Emailing.Graph\Emailing.Graph.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="GraphEmailingIntegrationTests.local.settings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="GraphEmailingIntegrationTests.local.settings.json" Condition="Exists('GraphEmailingIntegrationTests.local.settings.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Emailing.Tests\IntegrationTests\EmailingIntegrationTests.cs" Link="IntegrationTests\EmailingIntegrationTests.cs" />
    <Compile Include="..\Emailing.Tests\IntegrationTests\EmailingIntegrationTestsConfiguration.cs" Link="IntegrationTests\EmailingIntegrationTestsConfiguration.cs" />
  </ItemGroup>

</Project>
