<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="IntegrationTests\EmailingIntegrationTests.cs" />
    <Compile Remove="IntegrationTests\EmailingIntegrationTestsConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="IntegrationTests\EmailingIntegrationTests.cs" />
    <None Include="IntegrationTests\EmailingIntegrationTestsConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Emailing\Emailing.csproj" />
  </ItemGroup>

</Project>
