name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "releases/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore PosInformatique.Foundations.slnx

      - name: Build solution
        run: |
          dotnet build PosInformatique.Foundations.slnx \
          --configuration Release \
          --no-restore

      - name: Run tests (.NET 8.0)
        run: |
          dotnet test \
          --solution PosInformatique.Foundations.slnx \
          --configuration Release \
          --no-build \
          --coverage \
          --coverage-output-format cobertura \
          --coverage-settings CodeCoverage.runsettings \
          --report-trx \
          --results-directory ./TestResults \
          --framework net8.0

      - name: Run tests (.NET 9.0)
        run: |
          dotnet test \
          --solution PosInformatique.Foundations.slnx \
          --configuration Release \
          --no-build \
          --coverage \
          --coverage-output-format cobertura \
          --coverage-settings CodeCoverage.runsettings \
          --report-trx \
          --results-directory ./TestResults \
          --framework net9.0

      - name: Run tests (.NET 10.0)
        run: |
          dotnet test \
          --solution PosInformatique.Foundations.slnx \
          --configuration Release \
          --no-build \
          --coverage \
          --coverage-output-format cobertura \
          --coverage-settings CodeCoverage.runsettings \
          --report-trx \
          --results-directory ./TestResults \
          --framework net10.0
  
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            TestResults/**/*.trx
